from __future__ import annotations

from pathlib import Path
import json
import re
import subprocess

def slugify(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug[:48] or "generated-app"

def _safe_name(name: str, prompt: str) -> str:
    return slugify(name or prompt.split(".")[0])

def plan_generated_app(prompt: str, name: str = "") -> dict:
    app_name = _safe_name(name, prompt)
    files = [
        "README.md",
        "app.py",
        "pyproject.toml",
        "web/index.html",
        "web/static/app.css",
        "web/static/app.js",
        "tests/test_smoke.py",
        "scripts/test.sh",
        ".claude/context/APP_MISSION.md",
        ".claude/context/SESSION_STATE.md",
    ]
    return {
        "app_name": app_name,
        "prompt": prompt,
        "planned_files": files,
        "safe_defaults": ["stdlib server", "no secrets", "local tests", "browser UI", "importable health function"],
    }

def _generated_files(prompt: str, name: str) -> dict[str, str]:
    app_name = _safe_name(name, prompt)
    title = app_name.replace("-", " ").title()
    app_py = "\n".join([
        "from __future__ import annotations",
        "",
        "from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer",
        "from pathlib import Path",
        "import json",
        "",
        "APP_NAME = " + json.dumps(title),
        "APP_PROMPT = " + json.dumps(prompt),
        "ROOT = Path(__file__).resolve().parent",
        "",
        "def health_payload():",
        "    return {'ok': True, 'app': APP_NAME, 'prompt': APP_PROMPT}",
        "",
        "class Handler(BaseHTTPRequestHandler):",
        "    def send_json(self, payload, status=200):",
        "        data = json.dumps(payload, indent=2).encode()",
        "        self.send_response(status)",
        "        self.send_header('content-type', 'application/json')",
        "        self.send_header('content-length', str(len(data)))",
        "        self.end_headers()",
        "        self.wfile.write(data)",
        "    def send_bytes(self, data, content_type, status=200):",
        "        self.send_response(status)",
        "        self.send_header('content-type', content_type)",
        "        self.send_header('content-length', str(len(data)))",
        "        self.end_headers()",
        "        self.wfile.write(data)",
        "    def do_GET(self):",
        "        if self.path == '/api/health':",
        "            self.send_json(health_payload())",
        "            return",
        "        if self.path.startswith('/static/'):",
        "            rel = self.path.replace('/static/', '', 1)",
        "            file_path = ROOT / 'web/static' / rel",
        "            if file_path.exists():",
        "                ctype = 'text/css' if rel.endswith('.css') else 'application/javascript'",
        "                self.send_bytes(file_path.read_bytes(), ctype)",
        "                return",
        "        index = ROOT / 'web/index.html'",
        "        self.send_bytes(index.read_bytes() if index.exists() else ('<h1>' + APP_NAME + '</h1>').encode(), 'text/html; charset=utf-8')",
        "",
        "def run(host='127.0.0.1', port=8777):",
        "    server = ThreadingHTTPServer((host, port), Handler)",
        "    print(f'{APP_NAME}: http://{host}:{port}')",
        "    server.serve_forever()",
        "",
        "if __name__ == '__main__':",
        "    run()",
        "",
    ])
    return {
        "README.md": "# " + title + "\n\nGenerated by AI Workflow OS.\n\nPrompt:\n\n" + prompt + "\n\nRun:\n\npython3 app.py\n\nTest:\n\nbash scripts/test.sh\n",
        "pyproject.toml": "[project]\nname = " + json.dumps(app_name) + "\nversion = \"0.1.0\"\nrequires-python = \">=3.10\"\ndependencies = []\n",
        "app.py": app_py,
        "web/index.html": "<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>" + title + "</title><link rel=\"stylesheet\" href=\"/static/app.css\"></head><body><main><section class=\"hero\"><p class=\"badge\">generated app</p><h1>" + title + "</h1><p>" + prompt + "</p><button id=\"healthBtn\">Check Health</button></section><pre id=\"out\">Ready</pre></main><script src=\"/static/app.js\"></script></body></html>",
        "web/static/app.css": "body{margin:0;padding:24px;background:#07111f;color:#eef6ff;font-family:system-ui}.hero{max-width:900px;margin:0 auto;padding:32px;border:1px solid #28435f;border-radius:24px;background:linear-gradient(135deg,#102542,#0b1728)}h1{font-size:clamp(36px,7vw,80px)}button{padding:12px 18px;border-radius:14px;border:0;background:#53d2ff;color:#03101f;font-weight:800}pre{max-width:900px;margin:20px auto;padding:18px;background:#020812;border-radius:18px;overflow:auto}.badge{color:#9ee7ff}",
        "web/static/app.js": "document.getElementById('healthBtn').onclick=async()=>{const r=await fetch('/api/health');document.getElementById('out').textContent=JSON.stringify(await r.json(),null,2)};",
        "tests/test_smoke.py": "import importlib.util\nfrom pathlib import Path\nspec = importlib.util.spec_from_file_location('generated_app', Path(__file__).resolve().parents[1] / 'app.py')\nmod = importlib.util.module_from_spec(spec)\nspec.loader.exec_module(mod)\nassert mod.health_payload()['ok'] is True\nprint('PASS generated app smoke test')\n",
        "scripts/test.sh": "#!/usr/bin/env bash\nset -euo pipefail\ncd \"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")/..\" && pwd)\"\npython3 tests/test_smoke.py\n",
        ".claude/context/APP_MISSION.md": "# App Mission\n\nApp name: " + title + "\n\nPrompt:\n" + prompt + "\n\nGenerated by AI Workflow OS.\n",
        ".claude/context/SESSION_STATE.md": "# Session State\n\nGenerated app initialized.\n",
    }

def create_generated_app(prompt: str, target: Path, name: str = "", execute: bool = False) -> dict:
    plan = plan_generated_app(prompt, name)
    target = target.resolve()
    if not execute:
        plan["target"] = str(target)
        plan["executed"] = False
        return plan
    written = []
    for rel, text in _generated_files(prompt, name).items():
        path = target / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        if rel.endswith(".sh"):
            path.chmod(path.stat().st_mode | 0o755)
        written.append(rel)
    return {"target": str(target), "executed": True, "written": written, "plan": plan}

def test_generated_app(target: Path) -> dict:
    target = target.resolve()
    result = subprocess.run(["bash", "scripts/test.sh"], cwd=str(target), stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    return {"target": str(target), "ok": result.returncode == 0, "stdout": result.stdout, "stderr": result.stderr, "returncode": result.returncode}
