from __future__ import annotations

from pathlib import Path
import json
import re
import subprocess

def slugify(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug[:48] or "generated-app"

def create_generated_app(prompt: str, target: Path, name: str = "", execute: bool = False) -> dict:
    app_name = slugify(name or "generated-app")
    title = app_name.replace("-", " ").title()
    target = target.resolve()
    files = {
        "README.md": "# " + title + "\n\nGenerated by AI Workflow OS.\n\nPrompt:\n\n" + prompt + "\n",
        "app.py": "from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer\nfrom pathlib import Path\nimport json\nAPP_NAME=" + json.dumps(title) + "\nAPP_PROMPT=" + json.dumps(prompt) + "\nROOT=Path(__file__).resolve().parent\ndef health_payload(): return {\"ok\": True, \"app\": APP_NAME, \"prompt\": APP_PROMPT}\nclass Handler(BaseHTTPRequestHandler):\n    def send_json(self,payload,status=200):\n        data=json.dumps(payload,indent=2).encode(); self.send_response(status); self.send_header(\"content-type\",\"application/json\"); self.send_header(\"content-length\",str(len(data))); self.end_headers(); self.wfile.write(data)\n    def send_bytes(self,data,ctype,status=200):\n        self.send_response(status); self.send_header(\"content-type\",ctype); self.send_header(\"content-length\",str(len(data))); self.end_headers(); self.wfile.write(data)\n    def do_GET(self):\n        if self.path==\"/api/health\": self.send_json(health_payload()); return\n        if self.path.startswith(\"/static/\"):\n            rel=self.path.replace(\"/static/\",\"\",1); fp=ROOT/\"web/static\"/rel\n            if fp.exists(): self.send_bytes(fp.read_bytes(), \"text/css\" if rel.endswith(\".css\") else \"application/javascript\"); return\n        fp=ROOT/\"web/index.html\"; self.send_bytes(fp.read_bytes() if fp.exists() else (\"<h1>\"+APP_NAME+\"</h1>\").encode(), \"text/html; charset=utf-8\")\ndef run(host=\"127.0.0.1\", port=8777):\n    server=ThreadingHTTPServer((host,port),Handler); print(f\"{APP_NAME}: http://{host}:{port}\"); server.serve_forever()\nif __name__==\"__main__\": run()\n",
        "web/index.html": "<!doctype html><html><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>" + title + "</title><link rel=\"stylesheet\" href=\"/static/app.css\"></head><body><main><section><p>generated app</p><h1>" + title + "</h1><p>" + prompt + "</p><button id=\"b\">Check Health</button><pre id=\"o\">Ready</pre></section></main><script src=\"/static/app.js\"></script></body></html>",
        "web/static/app.css": "body{margin:0;padding:24px;background:#07111f;color:#eef6ff;font-family:system-ui}main{max-width:900px;margin:auto}section{border:1px solid #28435f;border-radius:24px;padding:28px;background:#0b1728}button{padding:12px 18px;border-radius:14px;border:0;background:#58d3ff;font-weight:900}pre{background:#020812;padding:18px;border-radius:16px;overflow:auto}",
        "web/static/app.js": "document.getElementById(\"b\").onclick=async()=>{const r=await fetch(\"/api/health\");document.getElementById(\"o\").textContent=JSON.stringify(await r.json(),null,2)}",
        "tests/test_smoke.py": "import importlib.util\nfrom pathlib import Path\nspec=importlib.util.spec_from_file_location(\"generated_app\", Path(__file__).resolve().parents[1]/\"app.py\")\nmod=importlib.util.module_from_spec(spec)\nspec.loader.exec_module(mod)\nassert mod.health_payload()[\"ok\"] is True\nprint(\"PASS generated app smoke test\")\n",
        "scripts/test.sh": "#!/usr/bin/env bash\nset -euo pipefail\ncd \"$(cd \"$(dirname \"${BASH_SOURCE[0]}\")/..\" && pwd)\"\npython3 tests/test_smoke.py\n",
        ".claude/context/APP_MISSION.md": "# App Mission\n\nApp name: " + title + "\n\nPrompt:\n" + prompt + "\n",
        ".claude/context/SESSION_STATE.md": "# Session State\n\nGenerated by AI Workflow OS.\n"
    }
    if not execute:
        return {"executed": False, "target": str(target), "app_name": app_name, "planned_files": sorted(files)}
    written = []
    for rel, text in files.items():
        p = target / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text)
        if rel.endswith(".sh"):
            p.chmod(p.stat().st_mode | 0o755)
        written.append(rel)
    return {"executed": True, "target": str(target), "app_name": app_name, "written": written}

def test_generated_app(target: Path) -> dict:
    result = subprocess.run(["bash", "scripts/test.sh"], cwd=str(target.resolve()), stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    return {"ok": result.returncode == 0, "target": str(target.resolve()), "stdout": result.stdout, "stderr": result.stderr, "returncode": result.returncode}
