from __future__ import annotations
from pathlib import Path
from typing import Any, Dict, List
from datetime import datetime, timezone
import json
import re
import subprocess
import uuid

from .prompt_bridge import next_approved_prompt, complete_prompt

ROOT = Path(__file__).resolve().parents[1]
RUN_DIR = ROOT / "ai_workflow_os" / "self_build_runs"
GENERATED_ROOT = ROOT / "generated_apps"

SECRET_PATTERNS = [
    re.compile("sk-[A-Za-z0-9_\\-]{12,}"),
    re.compile("sk-proj-[A-Za-z0-9_\\-]{12,}"),
    re.compile("ghp_[A-Za-z0-9_]{12,}"),
    re.compile("gsk_[A-Za-z0-9_]{12,}"),
    re.compile("vcp_[A-Za-z0-9_]{12,}"),
    re.compile("tgp_v1_[A-Za-z0-9_\\-]{12,}"),
    re.compile("AIza[A-Za-z0-9_\\-]{12,}"),
    re.compile("postgresql://[^\\s]+", re.IGNORECASE),
]

def now() -> str:
    return datetime.now(timezone.utc).isoformat()

def redact(text: str) -> str:
    out = text or ""
    for pattern in SECRET_PATTERNS:
        out = pattern.sub("[REDACTED_SECRET]", out)
    return out

def safe_slug(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", value.lower()).strip("-")
    return slug[:48] or "self-built-app"

def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")

def write_json(path: Path, data: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=True, default=str) + chr(10), encoding="utf-8")

def run(cmd: List[str], timeout: int = 120) -> Dict[str, Any]:
    p = subprocess.run(cmd, cwd=ROOT, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=timeout, shell=False)
    return {"cmd": cmd, "returncode": p.returncode, "ok": p.returncode == 0, "stdout": redact(p.stdout[-8000:]), "stderr": redact(p.stderr[-8000:])}

def self_build_manifest() -> Dict[str, Any]:
    return {
        "ok": True,
        "name": "self_build_executor",
        "purpose": "consume approved prompts and make repo-scoped allowlisted changes with proof",
        "raw_shell": False,
        "deploys": False,
        "uses_secrets": False,
        "writes_allowed": ["generated_apps/", "docs/generated/", "ai_workflow_os/self_build_runs/"],
        "endpoints": ["GET /api/self-build/manifest", "POST /api/self-build/run-next"],
        "bridge": {"from_command_1": "GET /api/prompts/next-approved", "to_command_3": "generated app manifests and phone wrapper metadata"},
    }

def plan_from_prompt(prompt: str) -> Dict[str, Any]:
    prompt = redact(prompt)
    slug = safe_slug(prompt)
    if "phone" in prompt.lower() and "wrapper" in prompt.lower():
        slug = "phone-wrapper-control-app"
    app_dir = GENERATED_ROOT / slug
    return {
        "ok": True,
        "slug": slug,
        "app_dir": str(app_dir.relative_to(ROOT)),
        "prompt": prompt,
        "actions": [
            {"kind": "mkdir", "path": str(app_dir.relative_to(ROOT))},
            {"kind": "write", "path": str((app_dir / "app.py").relative_to(ROOT))},
            {"kind": "write", "path": str((app_dir / "web" / "index.html").relative_to(ROOT))},
            {"kind": "write", "path": str((app_dir / "tests" / "test_health.py").relative_to(ROOT))},
            {"kind": "write", "path": str((app_dir / "APP_MANIFEST.json").relative_to(ROOT))},
        ],
    }

def materialize_generated_app(plan: Dict[str, Any]) -> Dict[str, Any]:
    slug = plan["slug"]
    app_dir = ROOT / plan["app_dir"]
    prompt = plan["prompt"]
    app_py = "from __future__ import annotations" + chr(10) + "import json" + chr(10) + "from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer" + chr(10) + "APP_NAME = " + repr(slug) + chr(10) + "PROMPT = " + repr(prompt) + chr(10) + "class Handler(BaseHTTPRequestHandler):" + chr(10) + "    def _send(self, data, status=200):" + chr(10) + "        raw = json.dumps(data, indent=2).encode()" + chr(10) + "        self.send_response(status)" + chr(10) + "        self.send_header(\"Content-Type\", \"application/json\")" + chr(10) + "        self.send_header(\"Content-Length\", str(len(raw)))" + chr(10) + "        self.end_headers()" + chr(10) + "        self.wfile.write(raw)" + chr(10) + "    def do_GET(self):" + chr(10) + "        if self.path.startswith(\"/api/health\"):" + chr(10) + "            self._send({\"ok\": True, \"app\": APP_NAME, \"prompt\": PROMPT})" + chr(10) + "        else:" + chr(10) + "            self._send({\"ok\": True, \"app\": APP_NAME, \"endpoints\": [\"/api/health\"]})" + chr(10) + "def main():" + chr(10) + "    ThreadingHTTPServer((\"127.0.0.1\", 8787), Handler).serve_forever()" + chr(10) + "if __name__ == \"__main__\":" + chr(10) + "    main()" + chr(10)
    html = "<!doctype html><html><head><meta charset=\"utf-8\"><title>" + slug + "</title></head><body><h1>" + slug + "</h1><p>Generated by AI Workflow OS self-build executor.</p><pre id=\"out\">Loading...</pre><script>fetch(\"/api/health\").then(r=>r.json()).then(j=>document.getElementById(\"out\").textContent=JSON.stringify(j,null,2)).catch(e=>document.getElementById(\"out\").textContent=e.message)</script></body></html>" + chr(10)
    test_py = "from pathlib import Path" + chr(10) + "def test_manifest_exists():" + chr(10) + "    assert Path(__file__).resolve().parents[1].joinpath(\"APP_MANIFEST.json\").exists()" + chr(10)
    manifest = {"ok": True, "name": slug, "prompt": prompt, "generated_by": "ai-workflow-os-self-build-executor", "created_at": now(), "health_endpoint": "/api/health", "inherits": ["no fake proof", "no silent button failure", "no secret printing", "runtime proof required", "compile proof required", "no module package shadowing", "no heredoc core build"]}
    write_text(app_dir / "app.py", app_py)
    write_text(app_dir / "web" / "index.html", html)
    write_text(app_dir / "tests" / "test_health.py", test_py)
    write_json(app_dir / "APP_MANIFEST.json", manifest)
    return {"ok": True, "app_dir": str(app_dir.relative_to(ROOT)), "files": ["app.py", "web/index.html", "tests/test_health.py", "APP_MANIFEST.json"]}

def run_next_self_build() -> Dict[str, Any]:
    RUN_DIR.mkdir(parents=True, exist_ok=True)
    run_id = str(uuid.uuid4())
    approved = next_approved_prompt()
    if not approved.get("prompt"):
        return {"ok": True, "run_id": run_id, "status": "no_approved_prompt"}
    prompt_record = approved["prompt"]
    plan = plan_from_prompt(prompt_record["prompt"])
    materialized = materialize_generated_app(plan)
    compile_result = run(["python3", "-m", "py_compile", str(ROOT / plan["app_dir"] / "app.py")])
    tests_result = run(["python3", "-m", "pytest", str(ROOT / plan["app_dir"] / "tests" / "test_health.py"), "-q"])
    workflow_result = run(["bash", "scripts/verify_workflow_app.sh"])
    result = {"ok": bool(materialized["ok"] and compile_result["ok"] and tests_result["ok"] and workflow_result["ok"]), "run_id": run_id, "prompt_id": prompt_record["id"], "plan": plan, "materialized": materialized, "compile": compile_result, "tests": tests_result, "workflow_verify": workflow_result, "created_at": now()}
    proof_path = RUN_DIR / (run_id + ".json")
    write_json(proof_path, result)
    result["proof_path"] = str(proof_path)
    complete_prompt(prompt_record["id"], result)
    return result
